version: '3'

services:
  lumi-admin:
    build: .
    ports:
      - "8002:8002"
    environment:
      - DATABASE_URL=mysql://root:root123@mysql:3306/xiaozhi
      - REDIS_URL=redis://redis:6379
      - NEXTAUTH_SECRET=d085a3a4-020c-4a29-b09b-8ba04c9738ff
      - NEXTAUTH_URL=http://localhost:8002/xiaozhi
      - NODE_ENV=production
    volumes:
      - ./data:/app/data
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=xiaozhi
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
  
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data: 